[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nginx']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'mkdir -p runtime/logs runtime/cache web/assets',
    'chmod -R 777 runtime',
    'chmod -R 777 web/assets',
    'chmod -R 755 web'
]

[start]
cmd = 'cd web && php -S 0.0.0.0:$PORT -t .'
