[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'mkdir -p runtime/logs runtime/cache web/assets',
    'chmod -R 755 runtime',
    'chmod -R 755 web/assets'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t web'
