[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'mkdir -p web/assets',
    'chmod 777 runtime',
    'chmod 777 web/assets'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t web'
